function ChainRingEncounterProbability(x,m,t,nChain,nRing,b)
% calculate the encounter probability between bead m of a Rouse chain of
% nChain beads, and the t bead in a Rouse ring of nRing beads. connected to the
% nChain bead of the chain. 
varChain = @(m,nChain,b)((b^2)/numel(x))*abs(nChain-m); % variance of the chain 
varRing  = @(t,nRing,b)((t./nRing).*(nRing-(t))*(b^2)/numel(x));% variance of the ring

% pdf of the chain 
fChain=@(x,m,nChain,b) ((1./(2*pi*varChain(m,nChain,b))).^(numel(x)/2)).*exp(-0.5*(x*x')./varChain(m,nChain,b));

% pdf of the ring 
fRing = @(x,t,nRing,b) ((1./(2*pi*varRing(t,nRing,b))).^(numel(x)/2)).*exp(-0.5*(x*x')./varRing(t,nRing,b));

% f = @(m,t,nChain,nRing,b)(varChain(m,nChain,b)+varRing(t,nRing,b))./(2*varChain(m,nChain,b).*varRing(t,nRing,b));
% g = @(x,m,nChain,b) (x)./varChain(m,nChain,b);
% h = @(x,m,nChain,b) -(x*x')./(2*varChain(m,nChain,b));
% k = @(x,m,t,nChain,nRing,b) (1./((4*pi^2).*varChain(m,nChain,b).*varRing(t,nRing,b))).^(1/2);

% fRC= @(x,m,t,nChain,nRing,b) ((k(x,m,t,nChain,nRing,b).*sqrt(pi./f(m,t,nChain,nRing,b))).^numel(x)).*...
%                             exp(((g(x,m,nChain,b)*g(x,m,nChain,b)')./(4*f(m,t,nChain,nRing,b))) +h(x,m,nChain,b));
fRC=@(x,m,t,nChain,nRing,b)((1./(2*pi.*(varChain(m,nChain,b)+varRing(t,nRing,b)))).^(numel(x)/2)).*...
    exp(-0.5*(x*x')./(varChain(m,nChain,b)+varRing(t,nRing,b)));

% % pdf of the chain-ring encounter 
% fRC=@(x,m,t,nChain,nRing,b)((1./(4*(pi^2)*varChain(m,nChain,b).*varRing(t,nRing,b))).^(0.5*numel(x))).*...
%     sqrt(2*pi.*varChain(m,nChain,b).*varRing(t,nRing,b)./(varChain(m,nChain,b)+varRing(t,nRing,b))).*...
%     exp(-0.5*(x*x').*(1-varRing(t,nRing,b)./(varChain(m,nChain,b).*(varRing(t,nRing,b)+varChain(m,nChain,b)))));

f= figure('Units','norm'); 
% a= axes('Parent',f,'NextPlot','Add','XScale','log','YScale','log','FontSize',30);
aScale={'linear','log'};
for n=1:2
a = subplot(1,2,n,'Parent',f,...
                'Units','norm',...
                'NextPlot','Add',...
                'XScale',aScale{n},...
                'YScale',aScale{n},...
                'FontSize',30);
xlabel(a,'Distance [bead]','FontSize',40);
ylabel(a,'Encounter Prob.','FontSize',40);

s=(sum(fChain(x,nChain-1:-1:m,nChain,b))+sum(fRC(x,1,t(2:end-1),nChain,nRing,b)));
line('XData',nChain+t-1,...
     'YData',fRC(x,m,t,nChain,nRing,b)./s,...
     'Color','b',...
     'Marker','o',...
     'MarkerSize',5,...
     'LineWidth',4,...
     'DisplayName','Ring encountes',...
     'Parent',a)

% connect the rouse chain 
line('XData',1:nChain-1,...
    'YData',fChain(x,nChain-1:-1:m,nChain,b)./s,...
    'Color','r',...
    'Marker','o',...
    'MarkerSize',5,...
    'LineWidth',4,...
    'DisplayName','Chain encounters',...
    'Parent',a);
legend(get(a,'Children'))
end
% % 
%  line('XData',nChain+t-1,...
%      'YData',fRing(x,t,nRing,b)./sum(fRing(x,t(2:end-1),nRing,b)),...
%      'Color','g',...
%      'Marker','.',...
%      'DisplayName','Chain',...
%      'Parent',a)
%  totalPts = [fChain(x,nChain-1:-1:m,nChain,b) fRC(x,m,t,nChain,nRing,b)];
%  hold on , plot(totalPts,'m')
%  c= conv([fChain(x,m:nChain-1,nChain,b)],[fRing(x,t,nRing,b)]);
 