function ChainRingEncounterProbability(x,m,t,nChain,nRing,b)
% calculate the encounter probability between bead m of a Rouse chain of
% nChain beads, and the t bead in a Rouse ring of nRing beads. connected to the
% nChain bead of the chain. 
varChain =@(m,nChain,b)((b^2))*abs(nChain-m); % variance of the chain 
varRing = @(t,nRing,b)((b^2))*((t).*(nRing-(t)));% variance of the ring

% pdf of the chain 
fChain=@(x,m,nChain,b) ((1./(2*pi*varChain(m,nChain,b))).^(numel(x)/2)).*exp(-0.5*(x*x')./varChain(m,nChain,b));

% pdf of the ring 
fRing = @(x,t,nRing,b) ((1./(2*pi*varRing(t,nRing,b))).^(numel(x)/2)).*exp(-0.5*(x*x')./varRing(t,nRing,b));

f = @(m,t,nChain,nRing,b)(varChain(m,nChain,b)+varRing(t,nRing,b))./(2*varChain(m,nChain,b).*varRing(t,nRing,b));
g = @(x,m,nChain,b) (x)./varChain(m,nChain,b);
h = @(x,m,nChain,b) -(x*x')./(2*varChain(m,nChain,b));
k = @(x,m,t,nChain,nRing,b) (numel(x)./((4*pi^2).*varChain(m,nChain,b).*varRing(t,nRing,b))).^(1/2);

fRC= @(x,m,t,nChain,nRing,b) ((k(x,m,t,nChain,nRing,b).*sqrt(pi./f(m,t,nChain,nRing,b))).^numel(x)).*...
                            exp(((g(x,m,nChain,b)*g(x,m,nChain,b)')./(4*f(m,t,nChain,nRing,b))) +h(x,m,nChain,b));
                        
% % pdf of the chain-ring encounter 
% fRC=@(x,m,t,nChain,nRing,b)((1./(4*(pi^2)*varChain(m,nChain,b).*varRing(t,nRing,b))).^(0.5*numel(x))).*...
%     sqrt(2*pi.*varChain(m,nChain,b).*varRing(t,nRing,b)./(varChain(m,nChain,b)+varRing(t,nRing,b))).*...
%     exp(-0.5*(x*x').*(1-varRing(t,nRing,b)./(varChain(m,nChain,b).*(varRing(t,nRing,b)+varChain(m,nChain,b)))));

f= figure;
a= axes('Parent',f,'NextPlot','Add');
line('XData',nChain+t-2,...
     'YData',fRC(x,m,t,nChain,nRing,b),...
     'Color','b',...
     'Marker','.',...
     'DisplayName','bead1_Ring',...
     'Parent',a)

% compare results to a rouse chain 
line('XData',1:nChain-1,...
    'YData',fChain(x,nChain-1:-1:m,nChain,b),...
    'Color','r',...
    'Marker','.',...
    'DisplayName','bead1_Chain',...
    'Parent',a);

 line('XData',nChain+t-2,...
     'YData',fRing(x,t,nRing,b),...
     'Color','g',...
     'Marker','.',...
     'DisplayName','Chain',...
     'Parent',a)
 