%scrSaveRelaxationConfiguration

% run chain to relaxation time 

% This test function moves histones on a Rouse chain
close all
% % create chain and domain and register them in the ObjectManager

% Initialize simulator framework parameters
simulatorParams = SimulationFrameworkParams('showSimulation',false,...
                                            'numSteps',1500,...
                                            'dt',0.01,...
                                            'objectInteraction',false);

% create an open domain
openSpaceForces = ForceManagerParams('lennardJonesForce',false,...
                                    'LJPotentialWidth',0.1,...
                                    'LJPotentialDepth',0.1,...
                                    'diffusionForce',true,...
                                    'diffusionConst',1,...                                    
                                    'mechanicalForce',false,...
                                    'mechanicalForceDirection','out',...
                                    'mechanicalForceCenter',[0 0 0],...
                                    'mechanicalForceMagnitude',0,...
                                    'dt',simulatorParams.simulator.dt);
dp(1)         = DomainHandlerParams('domainShape','open',...
                                    'reflectionType','off',...
                                    'forceParams',openSpaceForces,...
                                    'domainWidth',0,...
                                    'dimension',simulatorParams.simulator.dimension);


   
% % create a chain
chainForces = ForceManagerParams('dt',simulatorParams.simulator.dt,...
                                 'springForce',false,...
                                 'bendingElasticityForce',false,...
                                 'bendingConst',2,...
                                 'springConst',1,...
                                 'minParticleEqDistance',0);
                             
cp          = ChainParams('numBeads',500,...
                          'initializeInDomain',1,...
                          'forceParams',chainForces,...
                          'b',sqrt(3));

% create a sphere for visualization                                 
gSphereForce         = ForceManagerParams('lennardJonesForce',false,...
                                          'diffusionForce',false,...
                                          'morseForce',false,...
                                          'mechanicalForce',false);                                                                    
                      
% register the object parameters in the simulator framework
simulatorParams.SetDomainParams(dp);
simulatorParams.SetChainParams(cp);

% initialize simulator framework
r = RouseSimulatorFramework(simulatorParams);

% Run until relaxation time
r.Run;

% save result 
